- README.md
- setup.cfg
- src/biomappings/__main__.py
- src/biomappings/cli.py
- src/biomappings/resources/__init__.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/resources/predictions.tsv
- src/biomappings/templates/home.html
- src/biomappings/utils.py
- src/biomappings/wsgi.py
This PR adds a simple web interface for curation. It works by reading the predictions, positive mappings, and negative mappings files, then rewriting them when changes are requested by the user.  This PR also adds a CLI using click and entrypoints to make it easy to access the interface after pip installing.
It can be run with:
```bash
$ biomappings web
```
> Add web curation interface

- .flake8
- scripts/generate_mesh_uniprot_mappings.py
- scripts/import_gilda_mappings.py
- src/biomappings/__init__.py
- src/biomappings/resources/__init__.py
- src/biomappings/tests/test_validity.py
- src/biomappings/utils.py
- tox.ini
> Make MeSH-UniProt script more reusable and begin implementing helper functionality

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/templates/home.html
- src/biomappings/tests/test_validity.py
- src/biomappings/utils.py
- src/biomappings/wsgi.py
This PR adds a First/Last navigation button, mainly to be able to quickly jump to the end of the list. It also fixes identifiers.org URLs for namespaces whose IDs have the namespace embedded in them.
> Web app developments

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/templates/home.html
- src/biomappings/utils.py
- src/biomappings/wsgi.py
(Also adds auto-push to the commit button when you're not on master branch)
How it started
How its going
> Add search functionality

- docs/_data/summary.yml
- docs/index.md
- src/biomappings/cli.py
This PR adds another table to show statistics of curations per ORCID.
> Add contributors to website

- scripts/import_gilda_mappings.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
For reasons I don't fully understand, there were another 2.6k predictions from Gilda that were not imported in #6 so I'm adding those here.
> Import more Gilda predictions

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
the only ones left are the hard ones
> More GO curation

- setup.cfg
- src/biomappings/resources/mappings.tsv
- src/biomappings/templates/base.html
- src/biomappings/templates/home.html
- Update from bootstrap 3 to 4 by switching from unmaintained flask-bootstrap to bootstrap-flask (confusing, I know)
- Add confidence bars (with color!) to interface
- Right align line numbers
> Update web interface

- scripts/generate_ccle_mappings.py
- src/biomappings/__init__.py
- src/biomappings/cli.py
- src/biomappings/mapping_graph.py
- src/biomappings/resources/__init__.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/resources/unsure.tsv
- src/biomappings/tests/test_validity.py
This PR adds functionality to auto-sort the curated files. It also adds tests to make sure they're sorted before merging. 
It also adds prune functionality to remove predictions that can be inferred by a mappings graph generated on a given set of prefixes
> Add canonicalization of resources and pruning function

- src/biomappings/resources/__init__.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
> Fix autosorting on web application

- src/biomappings/resources/mappings.tsv
- src/biomappings/utils.py
- tests/test_validity.py
This PR adds some mappings I curated manually between PubChem and MeSH for breast cancer-related drugs.
Fixes #78
> Add manually curated PubChem-MeSH mappings

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/resources/unsure.tsv
This PR adds a few more curations for DOID-MeSH predicted mappings. There are still many remaining, typically poor quality and not trivial to review.
> More manual DOID-MeSH curation

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
This PR confirms a number of predictions that affect INDRA's resources.
> More curations

- .github/workflows/checks.yml
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/resources/unsure.tsv
- src/biomappings/templates/home.html
- src/biomappings/utils.py
- src/biomappings/wsgi.py
- tox.ini
1. Use comma separators in formatting of numbers
2. Don't show lines by default (it can be configured, now)
3. Allow for filtering to same_text=true
4. Do some mesh curation
> Improve interface

- src/biomappings/resources/mappings.tsv
This PR adds some MeSH-ChEBI curations, including some specific ones I needed.
> More MeSH-ChEBI curations

- src/biomappings/resources/curators.tsv
- src/biomappings/resources/incorrect.tsv
Curated 1 predicted mapping to incorrect mapping
> Curated 1 mapping (sumir)

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
Adding a few more CHEBI-MeSH equivalences that came up during Gilda grounding.
> More ChEBI-MeSH curations

- src/biomappings/__init__.py
- src/biomappings/lexical.py
- src/biomappings/resources/__init__.py
- src/biomappings/utils.py
- src/biomappings/wsgi.py
- fix exports
- make curator loading more reusable
> Minor updates

- src/biomappings/resources/positive.sssom.tsv
These mappings were curated via the Biomappings web app by [orcid:0000-0001-9439-5346](https://bioregistry.io/orcid%3A0000-0001-9439-5346).
> Curated 5 mappings via Biomappings web app

- src/biomappings/cli.py
- src/biomappings/templates/home.html
- src/biomappings/wsgi.py
This enables using a local bioregistry by argument like in `biomappings web --resolver-base http://localhost:5002`
> Add local resolver flag

- pyproject.toml
- src/biomappings/lexical.py
- tests/test_lexical.py
- tox.ini
This is a follow-up to #206 that enables batching on target ontologies
> Implement batching in embedding matching
