biopragmatics/biomappings

- mappings.tsv
Renames `source id` to `source identifier` to match `target identifier`.
> Standardize column name to identifier

- src/biomappings/tests/test_validity.py
The current redundancy check doesn't catch if the same equivalency shows up, but in the opposite order. This code sorts each equivalence into a "canonical" order where the first prefix should be earlier in sort order.
Caveats:
- ~What if two things are equivalent with same prefix? That's kind of silly, but it definitely happens in wikipathways!~ (solved in https://github.com/biomappings/biomappings/pull/10/commits/158e5c97b634cec55b9752b6341d47e37ccb36a6)
- Reporting will only show one direction
> Update redundancy test

- .github/workflows/checks.yml
- setup.cfg
Looks like everything is working down to Python 3.6+ so we might as well extend compatibility to facilitate integration (with e.g., INDRA).
> Extend Python version compatibility

- src/biomappings/templates/home.html
- src/biomappings/wsgi.py
This PR adds a very minimal input form to allow adding new mappings on the web interface. These can then be automatically committed along with any other curations.
> Add input form for adding mappings

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/templates/home.html
- src/biomappings/wsgi.py
If you add `?prefix=mesh` into the URL, it will filter based on that. It's not showing it in the UI right now.
I implemented this because I wanted to finish up some of the smaller lists, like `uniprot.chain`. I curated the last two and found that mapping to protein ontology should be done very carefully, since protein ontology's entries are species-specific and it mapped Dengue proteins in PRO to SARS-CoV-2 proteins in UniProt
> Add prefix filter

- src/biomappings/utils.py
This command has been silently erroring because of an extra `git`, and so it auto-pushed directly to master.
> Fix git command to check for main

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
In this PR I curated a good chunk of the predicted GO mappings. There are lots of new confirmed matches (314) but also a large number of ones that I marked as incorrect (70). The main reason certain matches were incorrect was a mismatch where a MeSH term represents an entity, e.g., `adenylylsulfate reductase`, and the corresponding GO term represents an activity, e.g., `adenylyl-sulfate reductase activity`. Certainly, there is a strong ontological connection between these but `skos:exactMatch` is probably not appropriate here.
The remaining GO mappings are more tricky to evaluate and would require looking more deeply at the individual entries.
> Curated 384 GO mappings

- scripts/kegg_mappings.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
This PR adds mappings from KEGG Pathway to GO and MeSH when possible. GO terms corresponding to cellular components and activities were automatically marked as incorrect, even in cases when the pathway was about that as a topic. For example, KEGG has a peroxisomes pathway and there is a cellular component in GO for peroxisomes, but these are not the same thing. KEGG also has many disease-specific pathways that mapped to MeSH names, but these are not the same either. Later, other ontological relationships could be assigned to map these together.
> Add KEGG pathway mappings

- src/biomappings/resources/mappings.tsv
- src/biomappings/utils.py
This PR removes FamPlex-MeSH predictions and mappings that are available via FamPlex directly (as a "primary" source) and should therefore not be duplicated here. It also adds some CHEBI-MeSH curations. Fixes #28.
> Remove redundant FamPlex-MeSH predictions and mappings

- setup.cfg
I think `flask-wtf` is required as a separate install requirement, I had to install it in a clean virtualenv in addition to flask and bootstrap-flask to make the webapp run.
> Add flask-wtf requirement

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
This PR adds manually curated mappings for protein fragments derived from SARS-CoV-2 Replicase polyprotein 1a and Replicase polyprotein 1ab between `ncbiprotein` and `uniprot.chain`. It also adds some random other reviewed curations from automated mappings.
> Add ncbiprotein-uniprot.chain mappings for SARS-CoV-2

- src/biomappings/resources/incorrect.tsv
This PR curates 9 predicted MESH-HGNC mappings as incorrect.
> Curated 9 mappings (ben)

- docs/_data/biomappings.sssom.tsv
- docs/_data/biomappings.sssom.yml
- src/biomappings/export_sssom.py
This PR creates an [SSSOM](https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md) export of biomappings. It can include not only curated mappings, but also predicted ones and their metadata.
See: https://github.com/biomappings/biomappings/blob/add-sssom-export/docs/_data/biomappings.sssom.tsv
Tasks:
Follow-up in future PR:
> Add SSSOM Export

- .flake8
- scripts/generate_ccle_mappings.py
- scripts/generate_mondo_mappings.py
- scripts/generate_pathway_mappings.py
- setup.cfg
- src/biomappings/gilda_utils.py
- src/biomappings/resources/mappings.tsv
- src/biomappings/utils.py
This PR refactors the PyOBO + Gilda prediction code. 
1. Support optionally using identifiers as names when generating Gilda terms. This is necessary for CCLE, FPLX, etc.
2. Support filtering out predictions for (source prefix, source id, target prefix) 3-tuples that are already in mappings loadable through PyOBO
3. Support filtering out custom sets, which I demonstrate by building up mappings for CCLE based on transitivities through DepMap, Cellosaurus, BTO, EFO, and CL. I also updated some of the code in PyOBO and Bioregistry to support this.
This PR also runs the CCLE mapping and generates plenty of novel curation opportunities. I added a few curations as examples. @ALHoyt can try doing the rest in the next few days.
CC @bgyori @stirlin6 these mappings will provide additional context …
> Update Gilda pipeline and add CCLE predictions

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/resources/unsure.tsv
This PR adds manual curations for some of the DOID mappings remaining after #79.
I also realized that EFO also provides mappings to DOID and these aren't symmetric with what DOID provides so have to be independently considered. So this PR removes all the DOID-EFO mappings where EFO already provides a mapping to DOID for a given EFO ID. This leaves only 137 remaining DOID-EFO mappings that are potentially useful.
> Remove more redundant predictions and curate some DOID mappings

- scripts/generate_uberon_mesh_mappings.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
This PR creates a set of predictions between UBERON and MeSH for UBERON entries where such a mapping is missing. I also confirmed 130 of the mappings as correct.
> Add UBERON-MeSH mappings

- scripts/generate_cl_mesh_mappings.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/resources/unsure.tsv
This PR adds a script to find missing mappings between CL and MESH to create 119 mappings. I curated 79 as correct, 38 as incorrect and 2 unsure. I then curated 2 more mappings manually.
> Predict and curate CL-MESH mappings

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
It made some more curations while examining predictions to/from MeSH. @cthoyt I am not entirely sure what happened but a chunk of mappings that are negative diffs in predictions.tsv don't show up as positive diffs in mappings.tsv, one example being 
```
chebi CHEBI:135421 fenalamide skos:exactMatch mesh C004341 fenalamide lexical 0.95 generate_chebi_mesh_mappings.py
```
I possibly messed something up in git manually, though there is also a possibility that the web app had a problem with adding some of the curations. We should sort these out before merging.
> Miscellaneous curation

- scripts/add_mesh_xrefs_to_mondo.py
- scripts/generate_mondo_mesh_mappings.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/utils.py
This PR predicts and then curates around 200 new mappings between MONDO and MeSH. These are restricted to cases where there isn't already a direct mapping in MONDO or an indirect xref path from MONDO (via e.g., DOID) to MeSH. By adding a `return` after the first check to `check_valid_prefix_id`, this resolves #94 but I'm not sure if this is the right solution to that.
> Curate MONDO-MeSH mappings

- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/utils.py
- tests/test_validity.py
Following https://github.com/biopragmatics/biomappings/pull/104#issuecomment-1263957329, this PR implements the change that we won't make assumptions about how Identifiers.org might curate future OBO Foundry ontologies' local unique identifier patterns. Therefore, this PR removes the redundant prefixes in MONDO's local unique identifiers.
This PR could be merged directly or also combine into #104 if the diff would be a problem
> Update MONDO local unique identifiers

- scripts/add_mesh_xrefs_to_doid_owl.py
- scripts/generate_doid_mappings.py
- scripts/generate_doid_mesh_mappings.py
- setup.cfg
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
This PR does the following:
- Add new DOID-MESH predictions based on a new script that predicts largely correct, one-to-one mappings
- Curates these new mappings to find 152 new correct mappings
- Adds a script to add _all_ non-redundant, curated DOID-MESH mappings (i.e., not just new ones but also ones that were curated earlier) to the editable OWL version of DOID in version control
Note that some, relatively less reliable predictions originally produced by https://github.com/biopragmatics/biomappings/blob/master/scripts/generate_doid_mappings.py were removed, though these do contain at least some correct predictions, though in principle, this new script would have found the same matches if they were non-redundant and one-to-one.
> Curate additional DOID-MESH mappings and contribute to DOID

- README.md
- docs/CONTRIBUTING.md
- docs/GOVERNANCE.md
This PR adds project contribution guidelines and governance, heavily inspired by the Bioregistry's guidelines and governance. The goal here is to add some rules to help bolster the sustainability of this project.
> Add project governance documentation

- scripts/generate_uberon_bto_mappings.py
- src/biomappings/resources/mappings.tsv
Addresses #128. This PR adds a script to generate simple UBERON-BTO mappings that are at the level of exact or approximate lexical matches using standard names. As far as I can tell, BTO doesn't maintain its own cross-references to UBERON, however, UBERON already maps to 1403 BTO IDs which we don't redundantly predict here. The script predicts 60 missing mappings. If useful, it could be extended to take synonyms into account in addition to standard names.
> Add UBERON-BTO predictions

- src/biomappings/resources/__init__.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
Before, redundant mapping filtering just checked that the tuple was the same. Now, it groups by the canonical tuple and uses a key for picking the "best" mapping. For now, this is a simple function. Later, it can be extended to take into account confidence in the curator, prediction methodology, or potentially extending the data model to keep track of the date of prediction/curation and just keep the earliest.
> Improve redundancy filtering

- src/biomappings/testing.py
- tests/test_validity.py
This is helpful in case you curate your own mappings somewhere else and still want to have a test case for them being internally right
> Make tests reusable

- src/biomappings/utils.py
There are OBI entries with 8 numbers - MIRIAM's regex is wrong.
> Override MIRIAM OBI pattern

- docs/_data/sssom/biomappings.sssom.yml
- src/biomappings/export_sssom.py
- src/biomappings/utils.py
As a follow-up to https://github.com/biopragmatics/biomappings/issues/154, this PR aligns the SSSOM export with OBO prefixes/URI prefixes. CC @gouttegd.
Built on top of https://github.com/biopragmatics/bioregistry/pull/939.
> Use preferred prefixes in SSSOM

- scripts/import_gilda_mappings.py
- src/biomappings/resources/incorrect.tsv
- src/biomappings/resources/mappings.tsv
- src/biomappings/wsgi.py
Related to https://github.com/gyorilab/gilda/pull/140, there are a lot of new predictions, and I curated a few instances here and there to improve results.
> Update MeSH predictions and curations
